version: 0.0
os: linux
files:
  - source:  /
    destination: /home/gksdydwns/app/
    overwrite: yes
file_exists_behavior : OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: gksdydwns
    group: gksdydwns

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: gksdydwns
